export const IntermediateFile = {
  language: 'language.json',
  monsterForms: 'monsterForms.json',
  monsterSpriteAnim: 'monsterSpriteAnim.json',
  monsterSpawn: 'monsterSpawn.json',
  moves: 'moves.json',
  characters: 'characters.json',
  characterSpriteAnim: 'characterSpriteAnim.json',
  characterSfx: 'characterSfx.json',
  elements: 'elements.json',
  elementReactions: 'elementReactions.json',
  elementReactionsGrid: 'elementReactionsGrid.json',
  elementReactionsOptions: 'elementReactionsOptions.json',
  statusEffects: 'statusEffects.json',
  fusion: 'fusion.json',
  fusionSpriteAnim: 'fusionSpriteAnim.json',
  world: 'world.json',
  version: 'version.json',

  misc: 'misc.json',
  assistantAppsLanguage: 'assistantApps.lang.json',
};
