export const IntermediateFile = {
  language: 'language.json',
  monsterForms: 'monsterForms.json',
  monsterSpriteAnim: 'monsterSpriteAnim.json',
  moves: 'moves.json',
  characters: 'characters.json',
  characterSpriteAnim: 'characterSpriteAnim.json',
  characterSfx: 'characterSfx.json',
  elements: 'elements.json',
  elementReactions: 'elementReactions.json',
  statusEffects: 'statusEffects.json',
  world: 'world.json',
  version: 'version.json',
  misc: 'misc.json',
};
